var students =[
    {
        "label": "Aldor",
        "IVIS": 7,
        "Stats": 3,
        "Math": 3,
        "Art": 9,
        "User": 6,
        "Prog": 2,
        "Graphics": 1,
        "HCI": 4,
        "UX": 8
    },
    {
        "label": "Aragorn",
        "IVIS": 5,
        "Stats": 4,
        "Math": 3,
        "Art": 6,
        "User": 7,
        "Prog": 3,
        "Graphics": 1,
        "HCI": 4,
        "UX": 8
    },
    {
        "label": "Arwen",
        "IVIS": 3,
        "Stats": 3,
        "Math": 3,
        "Art": 3,
        "User": 8,
        "Prog": 8,
        "Graphics": 3,
        "HCI": 3,
        "UX": 3
    },
    {
        "label": "Balin",
        "IVIS": 3,
        "Stats": 4,
        "Math": 4,
        "Art": 6,
        "User": 8,
        "Prog": 2,
        "Graphics": 1,
        "HCI": 2,
        "UX": 7
    },
    {
        "label": "Bereg",
        "IVIS": 3,
        "Stats": 5,
        "Math": 6,
        "Art": 8,
        "User": 6,
        "Prog": 3,
        "Graphics": 5,
        "HCI": 3,
        "UX": 5
    },
    {
        "label": "Bifur",
        "IVIS": 4,
        "Stats": 4,
        "Math": 5,
        "Art": 6,
        "User": 10,
        "Prog": 7,
        "Graphics": 7,
        "HCI": 6,
        "UX": 7
    },
    {
        "label": "Bilbo",
        "IVIS": 6,
        "Stats": 5,
        "Math": 8,
        "Art": 7,
        "User": 8,
        "Prog": 7,
        "Graphics": 7,
        "HCI": 7,
        "UX": 8
    },
    {
        "label": "Bofur",
        "IVIS": 4,
        "Stats": 4,
        "Math": 6,
        "Art": 5,
        "User": 7,
        "Prog": 7,
        "Graphics": 3,
        "HCI": 3,
        "UX": 2
    },
    {
        "label": "Bombadil",
        "IVIS": 4,
        "Stats": 6,
        "Math": 6,
        "Art": 2,
        "User": 6,
        "Prog": 5,
        "Graphics": 1,
        "HCI": 5,
        "UX": 8
    },
    {
        "label": "Bombur",
        "IVIS": 1,
        "Stats": 4,
        "Math": 5,
        "Art": 10,
        "User": 7,
        "Prog": 4,
        "Graphics": 2,
        "HCI": 3,
        "UX": 6
    },
    {
        "label": "Borin",
        "IVIS": 2,
        "Stats": 4,
        "Math": 2,
        "Art": 6,
        "User": 6,
        "Prog": 2,
        "Graphics": 1,
        "HCI": 4,
        "UX": 10
    },
    {
        "label": "Boromir",
        "IVIS": 3,
        "Stats": 5,
        "Math": 5,
        "Art": 1,
        "User": 7,
        "Prog": 8,
        "Graphics": 2,
        "HCI": 6,
        "UX": 5
    },
    {
        "label": "Bounder",
        "IVIS": 3,
        "Stats": 9,
        "Math": 9,
        "Art": 3,
        "User": 10,
        "Prog": 10,
        "Graphics": 3,
        "HCI": 3,
        "UX": 9
    },
    {
        "label": "Celeborn",
        "IVIS": 7,
        "Stats": 6,
        "Math": 5,
        "Art": 6,
        "User": 8,
        "Prog": 4,
        "Graphics": 1,
        "HCI": 6,
        "UX": 7
    },
    {
        "label": "Damrod",
        "IVIS": 3,
        "Stats": 2,
        "Math": 5,
        "Art": 6,
        "User": 7,
        "Prog": 1,
        "Graphics": 2,
        "HCI": 3,
        "UX": 8
    },
    {
        "label": "Deagol",
        "IVIS": 1,
        "Stats": 3,
        "Math": 3,
        "Art": 5,
        "User": 8,
        "Prog": 5,
        "Graphics": 1,
        "HCI": 1,
        "UX": 2
    },
    {
        "label": "Denethor",
        "IVIS": 7,
        "Stats": 8,
        "Math": 6,
        "Art": 2,
        "User": 8,
        "Prog": 9,
        "Graphics": 6,
        "HCI": 3,
        "UX": 6
    },
    {
        "label": "Dorlas",
        "IVIS": 4,
        "Stats": 4,
        "Math": 4,
        "Art": 6,
        "User": 5,
        "Prog": 4,
        "Graphics": 1,
        "HCI": 5,
        "UX": 6
    },
    {
        "label": "Dwalin",
        "IVIS": 3,
        "Stats": 3,
        "Math": 6,
        "Art": 7,
        "User": 7,
        "Prog": 6,
        "Graphics": 1,
        "HCI": 5,
        "UX": 5
    },
    {
        "label": "Eldarion",
        "IVIS": 3,
        "Stats": 4,
        "Math": 9,
        "Art": 8,
        "User": 8,
        "Prog": 3,
        "Graphics": 2,
        "HCI": 8,
        "UX": 9
    },
    {
        "label": "Elendil",
        "IVIS": 5,
        "Stats": 3,
        "Math": 5,
        "Art": 6,
        "User": 7,
        "Prog": 7,
        "Graphics": 4,
        "HCI": 6,
        "UX": 5
    },
    {
        "label": "Elendur",
        "IVIS": 3,
        "Stats": 3,
        "Math": 5,
        "Art": 2,
        "User": 7,
        "Prog": 5,
        "Graphics": 2,
        "HCI": 6,
        "UX": 9
    },
    {
        "label": "Elrond",
        "IVIS": 3,
        "Stats": 10,
        "Math": 8,
        "Art": 1,
        "User": 6,
        "Prog": 9,
        "Graphics": 4,
        "HCI": 3,
        "UX": 3
    },
    {
        "label": "Eomer",
        "IVIS": 7,
        "Stats": 9,
        "Math": 7,
        "Art": 3,
        "User": 9,
        "Prog": 8,
        "Graphics": 7,
        "HCI": 6,
        "UX": 1
    },
    {
        "label": "Eothain",
        "IVIS": 5,
        "Stats": 5,
        "Math": 7,
        "Art": 4,
        "User": 9,
        "Prog": 9,
        "Graphics": 8,
        "HCI": 4,
        "UX": 3
    },
    {
        "label": "Eowyn",
        "IVIS": 2,
        "Stats": 4,
        "Math": 4,
        "Art": 4,
        "User": 4,
        "Prog": 2,
        "Graphics": 6,
        "HCI": 4,
        "UX": 4
    },
    {
        "label": "Faramir",
        "IVIS": 5,
        "Stats": 4,
        "Math": 8,
        "Art": 7,
        "User": 9,
        "Prog": 8,
        "Graphics": 5,
        "HCI": 6,
        "UX": 6
    },
    {
        "label": "Ferny",
        "IVIS": 5,
        "Stats": 2,
        "Math": 3,
        "Art": 4,
        "User": 8,
        "Prog": 5,
        "Graphics": 3,
        "HCI": 4,
        "UX": 1
    },
    {
        "label": "Fili",
        "IVIS": 5,
        "Stats": 5,
        "Math": 5,
        "Art": 4,
        "User": 5,
        "Prog": 5,
        "Graphics": 4,
        "HCI": 5,
        "UX": 5
    },
    {
        "label": "Freda",
        "IVIS": 3,
        "Stats": 3,
        "Math": 9,
        "Art": 7,
        "User": 7,
        "Prog": 2,
        "Graphics": 2,
        "HCI": 3,
        "UX": 8
    },
    {
        "label": "Frodo",
        "IVIS": 3,
        "Stats": 3,
        "Math": 4,
        "Art": 4,
        "User": 6,
        "Prog": 5,
        "Graphics": 3,
        "HCI": 4,
        "UX": 3
    },
    {
        "label": "Galadriel",
        "IVIS": 7,
        "Stats": 5,
        "Math": 6,
        "Art": 7,
        "User": 9,
        "Prog": 8,
        "Graphics": 7,
        "HCI": 8,
        "UX": 5
    },
    {
        "label": "Gamgee",
        "IVIS": 2,
        "Stats": 4,
        "Math": 6,
        "Art": 2,
        "User": 7,
        "Prog": 6,
        "Graphics": 2,
        "HCI": 4,
        "UX": 3
    },
    {
        "label": "Gandalf",
        "IVIS": 4,
        "Stats": 6,
        "Math": 8,
        "Art": 1,
        "User": 9,
        "Prog": 8,
        "Graphics": 6,
        "HCI": 5,
        "UX": 5
    },
    {
        "label": "Gimli",
        "IVIS": 3,
        "Stats": 3,
        "Math": 4,
        "Art": 9,
        "User": 7,
        "Prog": 1,
        "Graphics": 1,
        "HCI": 1,
        "UX": 1
    },
    {
        "label": "Gollum",
        "IVIS": 4,
        "Stats": 2,
        "Math": 2,
        "Art": 4,
        "User": 9,
        "Prog": 1,
        "Graphics": 1,
        "HCI": 1,
        "UX": 6
    },
    {
        "label": "Gorbag",
        "IVIS": 5,
        "Stats": 2,
        "Math": 5,
        "Art": 5,
        "User": 9,
        "Prog": 7,
        "Graphics": 3,
        "HCI": 6,
        "UX": 3
    },
    {
        "label": "Grimbold",
        "IVIS": 4,
        "Stats": 4,
        "Math": 7,
        "Art": 5,
        "User": 9,
        "Prog": 6,
        "Graphics": 1,
        "HCI": 1,
        "UX": 4
    },
    {
        "label": "Grishnakh",
        "IVIS": 5,
        "Stats": 8,
        "Math": 6,
        "Art": 2,
        "User": 7,
        "Prog": 8,
        "Graphics": 5,
        "HCI": 4,
        "UX": 3
    },
    {
        "label": "Haldir",
        "IVIS": 3,
        "Stats": 3,
        "Math": 4,
        "Art": 7,
        "User": 8,
        "Prog": 2,
        "Graphics": 1,
        "HCI": 2,
        "UX": 2
    },
    {
        "label": "Haleth",
        "IVIS": 2,
        "Stats": 3,
        "Math": 3,
        "Art": 4,
        "User": 6,
        "Prog": 3,
        "Graphics": 1,
        "HCI": 4,
        "UX": 5
    },
    {
        "label": "Hama",
        "IVIS": 7,
        "Stats": 8,
        "Math": 8,
        "Art": 7,
        "User": 9,
        "Prog": 8,
        "Graphics": 8,
        "HCI": 7,
        "UX": 8
    },
    {
        "label": "Hardang",
        "IVIS": 2,
        "Stats": 4,
        "Math": 7,
        "Art": 9,
        "User": 7,
        "Prog": 2,
        "Graphics": 2,
        "HCI": 3,
        "UX": 8
    },
    {
        "label": "Idril",
        "IVIS": 6,
        "Stats": 3,
        "Math": 3,
        "Art": 8,
        "User": 10,
        "Prog": 5,
        "Graphics": 3,
        "HCI": 5,
        "UX": 5
    },
    {
        "label": "Irolas",
        "IVIS": 5,
        "Stats": 4,
        "Math": 5,
        "Art": 2,
        "User": 7,
        "Prog": 7,
        "Graphics": 4,
        "HCI": 6,
        "UX": 5
    },
    {
        "label": "Isildur",
        "IVIS": 4,
        "Stats": 5,
        "Math": 5,
        "Art": 4,
        "User": 8,
        "Prog": 8,
        "Graphics": 3,
        "HCI": 5,
        "UX": 5
    },
    {
        "label": "Kili",
        "IVIS": 3,
        "Stats": 5,
        "Math": 5,
        "Art": 1,
        "User": 6,
        "Prog": 6,
        "Graphics": 3,
        "HCI": 5,
        "UX": 8
    },
    {
        "label": "Legolas",
        "IVIS": 4,
        "Stats": 4,
        "Math": 4,
        "Art": 7,
        "User": 8,
        "Prog": 8,
        "Graphics": 4,
        "HCI": 4,
        "UX": 4
    },
    {
        "label": "Lindir",
        "IVIS": 2,
        "Stats": 2,
        "Math": 5,
        "Art": 2,
        "User": 7,
        "Prog": 4,
        "Graphics": 1,
        "HCI": 4,
        "UX": 4
    },
    {
        "label": "Lurtz",
        "IVIS": 3,
        "Stats": 6,
        "Math": 7,
        "Art": 6,
        "User": 8,
        "Prog": 8,
        "Graphics": 3,
        "HCI": 4,
        "UX": 5
    },
    {
        "label": "Madril",
        "IVIS": 4,
        "Stats": 4,
        "Math": 5,
        "Art": 4,
        "User": 9,
        "Prog": 5,
        "Graphics": 2,
        "HCI": 7,
        "UX": 5
    },
    {
        "label": "Maiar",
        "IVIS": 6,
        "Stats": 5,
        "Math": 5,
        "Art": 7,
        "User": 7,
        "Prog": 4,
        "Graphics": 2,
        "HCI": 5,
        "UX": 6
    },
    {
        "label": "Mauhur",
        "IVIS": 7,
        "Stats": 2,
        "Math": 5,
        "Art": 8,
        "User": 9,
        "Prog": 6,
        "Graphics": 2,
        "HCI": 6,
        "UX": 7
    },
    {
        "label": "Merry",
        "IVIS": 5,
        "Stats": 6,
        "Math": 7,
        "Art": 8,
        "User": 7,
        "Prog": 6,
        "Graphics": 4,
        "HCI": 4,
        "UX": 8
    },
    {
        "label": "Morwen",
        "IVIS": 3,
        "Stats": 5,
        "Math": 4,
        "Art": 3,
        "User": 10,
        "Prog": 6,
        "Graphics": 2,
        "HCI": 7,
        "UX": 5
    },
    {
        "label": "Nessa",
        "IVIS": 1,
        "Stats": 1,
        "Math": 1,
        "Art": 2,
        "User": 2,
        "Prog": 1,
        "Graphics": 1,
        "HCI": 1,
        "UX": 2
    },
    {
        "label": "Ohtar",
        "IVIS": 2,
        "Stats": 2,
        "Math": 1,
        "Art": 3,
        "User": 4,
        "Prog": 4,
        "Graphics": 1,
        "HCI": 2,
        "UX": 2
    },
    {
        "label": "Oin",
        "IVIS": 7,
        "Stats": 5,
        "Math": 8,
        "Art": 5,
        "User": 8,
        "Prog": 9,
        "Graphics": 7,
        "HCI": 9,
        "UX": 7
    },
    {
        "label": "Otho",
        "IVIS": 6,
        "Stats": 3,
        "Math": 4,
        "Art": 6,
        "User": 10,
        "Prog": 7,
        "Graphics": 5,
        "HCI": 9,
        "UX": 7
    },
    {
        "label": "Pelendur",
        "IVIS": 2,
        "Stats": 5,
        "Math": 4,
        "Art": 3,
        "User": 4,
        "Prog": 5,
        "Graphics": 4,
        "HCI": 4,
        "UX": 1
    },
    {
        "label": "Pippin",
        "IVIS": 7,
        "Stats": 2,
        "Math": 2,
        "Art": 8,
        "User": 10,
        "Prog": 7,
        "Graphics": 2,
        "HCI": 5,
        "UX": 2
    },
    {
        "label": "Quickbeam",
        "IVIS": 3,
        "Stats": 3,
        "Math": 5,
        "Art": 8,
        "User": 8,
        "Prog": 2,
        "Graphics": 3,
        "HCI": 3,
        "UX": 3
    },
    {
        "label": "Rian",
        "IVIS": 3,
        "Stats": 5,
        "Math": 5,
        "Art": 2,
        "User": 8,
        "Prog": 5,
        "Graphics": 3,
        "HCI": 4,
        "UX": 4
    },
    {
        "label": "Sam",
        "IVIS": 6,
        "Stats": 3,
        "Math": 5,
        "Art": 9,
        "User": 8,
        "Prog": 4,
        "Graphics": 4,
        "HCI": 4,
        "UX": 9
    },
    {
        "label": "Sauron",
        "IVIS": 3,
        "Stats": 9,
        "Math": 7,
        "Art": 2,
        "User": 9,
        "Prog": 6,
        "Graphics": 5,
        "HCI": 3,
        "UX": 3
    },
    {
        "label": "Shagrat",
        "IVIS": 3,
        "Stats": 3,
        "Math": 5,
        "Art": 6,
        "User": 7,
        "Prog": 2,
        "Graphics": 1,
        "HCI": 1,
        "UX": 4
    },
    {
        "label": "Sharku",
        "IVIS": 2,
        "Stats": 7,
        "Math": 5,
        "Art": 4,
        "User": 6,
        "Prog": 1,
        "Graphics": 1,
        "HCI": 1,
        "UX": 8
    },
    {
        "label": "Smaug",
        "IVIS": 7,
        "Stats": 4,
        "Math": 4,
        "Art": 6,
        "User": 10,
        "Prog": 8,
        "Graphics": 5,
        "HCI": 7,
        "UX": 6
    },
    {
        "label": "Smeagol",
        "IVIS": 3,
        "Stats": 3,
        "Math": 5,
        "Art": 7,
        "User": 9,
        "Prog": 3,
        "Graphics": 2,
        "HCI": 3,
        "UX": 8
    },
    {
        "label": "Theoden",
        "IVIS": 3,
        "Stats": 5,
        "Math": 8,
        "Art": 1,
        "User": 9,
        "Prog": 2,
        "Graphics": 1,
        "HCI": 1,
        "UX": 3
    },
    {
        "label": "Theodred",
        "IVIS": 4,
        "Stats": 8,
        "Math": 8,
        "Art": 5,
        "User": 9,
        "Prog": 7,
        "Graphics": 9,
        "HCI": 8,
        "UX": 4
    },
    {
        "label": "Thorin",
        "IVIS": 7,
        "Stats": 6,
        "Math": 7,
        "Art": 2,
        "User": 10,
        "Prog": 8,
        "Graphics": 6,
        "HCI": 7,
        "UX": 7
    },
    {
        "label": "Ugluk",
        "IVIS": 4,
        "Stats": 3,
        "Math": 5,
        "Art": 5,
        "User": 8,
        "Prog": 6,
        "Graphics": 4,
        "HCI": 4,
        "UX": 2
    },
    {
        "label": "Uruk",
        "IVIS": 5,
        "Stats": 8,
        "Math": 7,
        "Art": 7,
        "User": 9,
        "Prog": 9,
        "Graphics": 8,
        "HCI": 7,
        "UX": 7
    }
];